### ISSUE TITLE
Appending info to Dom.

### ISSUE THREAD

**Issue by frankcollins3** [frankcollins3/skyfightgame#1]
I created a set of 100 squares using 2 10 by 10 for loops.
I gave them an id, and all the DIVs with their ID's run through the console no problem.
I tried to append it to the page using appendChild(), and alternatively tried to  use   .classList.Add(' ')   w/  CSS to get visibility on the info I can see in the DOM. 

if you can plz help ty. looking into it myself atm as well.

**Comment by romebell** [comment]
<img width="790" alt="Screen Shot 2020-11-06 at 5 23 49 AM" src="https://user-images.githubusercontent.com/13144457/98371042-601c1f80-1ff0-11eb-9804-1401aa9d983d.png">
@frankcollins3 I don't see any code on your repo.

**Comment by frankcollins3** [comment]
I Thought I had committed it. I will re-do that

**Comment by romebell** [comment]
@frankcollins3 Still don't see code.

**Comment by romebell** [comment]
@frankcollins3 please reopen if you're running into this issue again.

Good to go. Issue closed ✅
